[build]
  command = 'npm run build'
  functions = 'functions'
  publish = 'build'

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:param"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
