export { default as logo 			} from './_logo'
export { default as auth 			} from './_auth'
export { default as banner 		} from './_banner'
export { default as jumbotron	} from './_jumbotron'
export { default as faq 			} from './_faq'
export { default as footer 		} from './_footer'
